// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: user.sql

package database

import (
	"context"
)

const findUserByMssv = `-- name: FindUserByMssv :one
SELECT 
    id, name, age, mssv 
FROM users 
WHERE mssv = $1
`

func (q *Queries) FindUserByMssv(ctx context.Context, mssv string) (Users, error) {
	row := q.db.QueryRowContext(ctx, findUserByMssv, mssv)
	var i Users
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Age,
		&i.Mssv,
	)
	return i, err
}
